// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rectangle.proto

// Protobuf Java Version: 3.25.2
package com.demo.libraries.proto;

public final class RectangleOuterClass {
  private RectangleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RectangleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.demo.libraries.proto.Rectangle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 x1 = 1;</code>
     * @return The x1.
     */
    int getX1();

    /**
     * <code>int32 x2 = 2;</code>
     * @return The x2.
     */
    int getX2();

    /**
     * <code>int32 y1 = 3;</code>
     * @return The y1.
     */
    int getY1();

    /**
     * <code>int32 y2 = 4;</code>
     * @return The y2.
     */
    int getY2();
  }
  /**
   * Protobuf type {@code com.demo.libraries.proto.Rectangle}
   */
  public static final class Rectangle extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.demo.libraries.proto.Rectangle)
      RectangleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Rectangle.newBuilder() to construct.
    private Rectangle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rectangle() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Rectangle();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.libraries.proto.RectangleOuterClass.internal_static_com_demo_libraries_proto_Rectangle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.libraries.proto.RectangleOuterClass.internal_static_com_demo_libraries_proto_Rectangle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.libraries.proto.RectangleOuterClass.Rectangle.class, com.demo.libraries.proto.RectangleOuterClass.Rectangle.Builder.class);
    }

    public static final int X1_FIELD_NUMBER = 1;
    private int x1_ = 0;
    /**
     * <code>int32 x1 = 1;</code>
     * @return The x1.
     */
    @java.lang.Override
    public int getX1() {
      return x1_;
    }

    public static final int X2_FIELD_NUMBER = 2;
    private int x2_ = 0;
    /**
     * <code>int32 x2 = 2;</code>
     * @return The x2.
     */
    @java.lang.Override
    public int getX2() {
      return x2_;
    }

    public static final int Y1_FIELD_NUMBER = 3;
    private int y1_ = 0;
    /**
     * <code>int32 y1 = 3;</code>
     * @return The y1.
     */
    @java.lang.Override
    public int getY1() {
      return y1_;
    }

    public static final int Y2_FIELD_NUMBER = 4;
    private int y2_ = 0;
    /**
     * <code>int32 y2 = 4;</code>
     * @return The y2.
     */
    @java.lang.Override
    public int getY2() {
      return y2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x1_ != 0) {
        output.writeInt32(1, x1_);
      }
      if (x2_ != 0) {
        output.writeInt32(2, x2_);
      }
      if (y1_ != 0) {
        output.writeInt32(3, y1_);
      }
      if (y2_ != 0) {
        output.writeInt32(4, y2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x1_);
      }
      if (x2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, x2_);
      }
      if (y1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, y1_);
      }
      if (y2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, y2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.libraries.proto.RectangleOuterClass.Rectangle)) {
        return super.equals(obj);
      }
      com.demo.libraries.proto.RectangleOuterClass.Rectangle other = (com.demo.libraries.proto.RectangleOuterClass.Rectangle) obj;

      if (getX1()
          != other.getX1()) return false;
      if (getX2()
          != other.getX2()) return false;
      if (getY1()
          != other.getY1()) return false;
      if (getY2()
          != other.getY2()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X1_FIELD_NUMBER;
      hash = (53 * hash) + getX1();
      hash = (37 * hash) + X2_FIELD_NUMBER;
      hash = (53 * hash) + getX2();
      hash = (37 * hash) + Y1_FIELD_NUMBER;
      hash = (53 * hash) + getY1();
      hash = (37 * hash) + Y2_FIELD_NUMBER;
      hash = (53 * hash) + getY2();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.libraries.proto.RectangleOuterClass.Rectangle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.libraries.proto.Rectangle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.demo.libraries.proto.Rectangle)
        com.demo.libraries.proto.RectangleOuterClass.RectangleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.libraries.proto.RectangleOuterClass.internal_static_com_demo_libraries_proto_Rectangle_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.libraries.proto.RectangleOuterClass.internal_static_com_demo_libraries_proto_Rectangle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.libraries.proto.RectangleOuterClass.Rectangle.class, com.demo.libraries.proto.RectangleOuterClass.Rectangle.Builder.class);
      }

      // Construct using com.demo.libraries.proto.RectangleOuterClass.Rectangle.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x1_ = 0;
        x2_ = 0;
        y1_ = 0;
        y2_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.libraries.proto.RectangleOuterClass.internal_static_com_demo_libraries_proto_Rectangle_descriptor;
      }

      @java.lang.Override
      public com.demo.libraries.proto.RectangleOuterClass.Rectangle getDefaultInstanceForType() {
        return com.demo.libraries.proto.RectangleOuterClass.Rectangle.getDefaultInstance();
      }

      @java.lang.Override
      public com.demo.libraries.proto.RectangleOuterClass.Rectangle build() {
        com.demo.libraries.proto.RectangleOuterClass.Rectangle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.demo.libraries.proto.RectangleOuterClass.Rectangle buildPartial() {
        com.demo.libraries.proto.RectangleOuterClass.Rectangle result = new com.demo.libraries.proto.RectangleOuterClass.Rectangle(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.demo.libraries.proto.RectangleOuterClass.Rectangle result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x1_ = x1_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.x2_ = x2_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.y1_ = y1_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.y2_ = y2_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.libraries.proto.RectangleOuterClass.Rectangle) {
          return mergeFrom((com.demo.libraries.proto.RectangleOuterClass.Rectangle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.libraries.proto.RectangleOuterClass.Rectangle other) {
        if (other == com.demo.libraries.proto.RectangleOuterClass.Rectangle.getDefaultInstance()) return this;
        if (other.getX1() != 0) {
          setX1(other.getX1());
        }
        if (other.getX2() != 0) {
          setX2(other.getX2());
        }
        if (other.getY1() != 0) {
          setY1(other.getY1());
        }
        if (other.getY2() != 0) {
          setY2(other.getY2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                x1_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                x2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                y1_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                y2_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int x1_ ;
      /**
       * <code>int32 x1 = 1;</code>
       * @return The x1.
       */
      @java.lang.Override
      public int getX1() {
        return x1_;
      }
      /**
       * <code>int32 x1 = 1;</code>
       * @param value The x1 to set.
       * @return This builder for chaining.
       */
      public Builder setX1(int value) {

        x1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x1_ = 0;
        onChanged();
        return this;
      }

      private int x2_ ;
      /**
       * <code>int32 x2 = 2;</code>
       * @return The x2.
       */
      @java.lang.Override
      public int getX2() {
        return x2_;
      }
      /**
       * <code>int32 x2 = 2;</code>
       * @param value The x2 to set.
       * @return This builder for chaining.
       */
      public Builder setX2(int value) {

        x2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearX2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x2_ = 0;
        onChanged();
        return this;
      }

      private int y1_ ;
      /**
       * <code>int32 y1 = 3;</code>
       * @return The y1.
       */
      @java.lang.Override
      public int getY1() {
        return y1_;
      }
      /**
       * <code>int32 y1 = 3;</code>
       * @param value The y1 to set.
       * @return This builder for chaining.
       */
      public Builder setY1(int value) {

        y1_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 y1 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearY1() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y1_ = 0;
        onChanged();
        return this;
      }

      private int y2_ ;
      /**
       * <code>int32 y2 = 4;</code>
       * @return The y2.
       */
      @java.lang.Override
      public int getY2() {
        return y2_;
      }
      /**
       * <code>int32 y2 = 4;</code>
       * @param value The y2 to set.
       * @return This builder for chaining.
       */
      public Builder setY2(int value) {

        y2_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 y2 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearY2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y2_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.demo.libraries.proto.Rectangle)
    }

    // @@protoc_insertion_point(class_scope:com.demo.libraries.proto.Rectangle)
    private static final com.demo.libraries.proto.RectangleOuterClass.Rectangle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.libraries.proto.RectangleOuterClass.Rectangle();
    }

    public static com.demo.libraries.proto.RectangleOuterClass.Rectangle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rectangle>
        PARSER = new com.google.protobuf.AbstractParser<Rectangle>() {
      @java.lang.Override
      public Rectangle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Rectangle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rectangle> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.demo.libraries.proto.RectangleOuterClass.Rectangle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_libraries_proto_Rectangle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_libraries_proto_Rectangle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017rectangle.proto\022\030com.demo.libraries.pr" +
      "oto\";\n\tRectangle\022\n\n\002x1\030\001 \001(\005\022\n\n\002x2\030\002 \001(\005" +
      "\022\n\n\002y1\030\003 \001(\005\022\n\n\002y2\030\004 \001(\005B\032\n\030com.demo.lib" +
      "raries.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_demo_libraries_proto_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_libraries_proto_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_libraries_proto_Rectangle_descriptor,
        new java.lang.String[] { "X1", "X2", "Y1", "Y2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
